source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'
use_frameworks!

def shared_pods
	pod 'KeychainSwift'
	pod 'Kingfisher'
end

target 'AxeptioSDK' do
	shared_pods
end

target 'Test' do
	shared_pods
end
